### ISSUE TITLE
Loop Reports Document Property Errors When Empty

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#108]
## Page Template effected
Loop Group Reports

## Behavior
When a report module does not have a page or document linked to it it results in an error. The page saves in the Wagtail editor, but when viewed on Loop the Reports page and the parent Group page both result in an Internal Server Error.

### Stack Trace
```
[2018-10-22 15:28:18,050] (99482/34602153984) django.request ERROR: Internal Server Error: /groups/staff-meeting/
Traceback (most recent call last):
  File "/data/motacilla/venv3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/data/motacilla/venv3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/motacilla/venv3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/motacilla/venv3.6/lib/python3.6/site-packages/wagtail/core/views.py", line 24, in serve
    return page.serve(request, *args, **kwargs)
  File "/data/motacilla/venv3.6/lib/python3.6/site-packages/wagtail/core/models.py", line 720, in serve
    self.get_context(request, *args, **kwargs)
  File "/data/motacilla/sites/library_website/group/models.py", line 297, in get_context
    if not r.link and not r.document.url:
AttributeError: 'GroupReportsPageTable' object has no attribute 'document'
```

## Possible Solution
Brad and John determined that the code is blowing up on the document property of reports when it’s doing a simple check to see if it exists or not. He believes that putting a put a try/except there would help solve this error.

**Comment by bbusenius** [comment]
I believe this has been resolved.
