### ISSUE TITLE
Fix lib_collections unit tests

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/library_website#389]
## Expected behavior
Unit tests should pass when we run `./manage.py test` on any server.

## Actual behavior
Unit tests are failing on `nest` and in Travis CI.

### Steps to reproduce
Run `./manage.py test`. The tests should fail with the following output:

```
======================================================================
FAIL: test_collections_digital (lib_collections.tests.test_lib_collections_view)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/data/nest/sites/library_website/lib_collections/tests.py", line 58, in test_collections_digital
    self.assertContains(response, '<input name="digital" type="checkbox" arial-label="limit to digital collections" id="checkboxdigital" checked="checked">', html=True)
  File "/data/nest/venv3.7/lib/python3.7/site-packages/django/test/testcases.py", line 446, in assertContains
    response, text, status_code, msg_prefix, html)
  File "/data/nest/venv3.7/lib/python3.7/site-packages/django/test/testcases.py", line 432, in _assert_contains
    content = assert_and_parse_html(self, content, None, "Response's content is not valid HTML:")
  File "/data/nest/venv3.7/lib/python3.7/site-packages/django/test/testcases.py", line 65, in assert_and_parse_html
    self.fail(self._formatMessage(user_msg, standardMsg))
  File "/usr/local/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: Response's content is not valid HTML:
('Unexpected end tag `li` (Line 347, Column 24)', (347, 24))

----------------------------------------------------------------------
Ran 79 tests in 583.275s

FAILED (failures=1)
```

### Related code
Line `58` in `library_website/lib_collections/tests.py`

## Other information:
HTML wasn't valid so the test was breaking. This was due to a redundant `</li>` close tag in the main navigation.

**Comment by bbusenius** [comment]
It looks like there are more problems with tests than just the error above. I get the following when I run them from a Vagrantized environment at home: 

```
======================================================================
ERROR: test_all_live_public_pages_for_200_or_redirect_with_anonymous_user (base.tests.TestUsersAndServingLivePages)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/base/tests.py", line 241, in test_all_live_public_pages_for_200_or_redirect_with_anonymous_user
    page.url, HTTP_HOST=site.hostname
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/client.py", line 518, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/client.py", line 346, in get
    **extra,
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/client.py", line 421, in generic
    return self.request(**r)
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/client.py", line 496, in request
    raise exc_value
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/lw/lib/python3.6/site-packages/wagtail/core/views.py", line 24, in serve
    return page.serve(request, *args, **kwargs)
  File "/home/vagrant/lw/lib/python3.6/site-packages/wagtail/core/models.py", line 771, in serve
    self.get_context(request, *args, **kwargs)
  File "/vagrant/findingaids/models.py", line 136, in get_context
    browses = get_browses()
  File "/vagrant/findingaids/models.py", line 18, in get_browses
    r = urllib.request.urlopen("http://marklogic.lib.uchicago.edu:8011/admin/gimme.xqy?collection=institution%2FUniversity%20of%20Chicago")
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

======================================================================
FAIL: test_collections_digital (lib_collections.tests.test_lib_collections_view)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/testcases.py", line 62, in assert_and_parse_html
    dom = parse_html(html)
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/html.py", line 220, in parse_html
    parser.feed(html)
  File "/usr/local/lib/python3.6/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.6/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
django.test.html.HTMLParseError: ('Unexpected end tag `li` (Line 347, Column 24)', (347, 24))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/lib_collections/tests.py", line 58, in test_collections_digital
    self.assertContains(response, '<input name="digital" type="checkbox" arial-label="limit to digital collections" id="checkboxdigital" checked="checked">', html=True)
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/testcases.py", line 446, in assertContains
    response, text, status_code, msg_prefix, html)
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/testcases.py", line 432, in _assert_contains
    content = assert_and_parse_html(self, content, None, "Response's content is not valid HTML:")
  File "/home/vagrant/lw/lib/python3.6/site-packages/django/test/testcases.py", line 65, in assert_and_parse_html
    self.fail(self._formatMessage(user_msg, standardMsg))
AssertionError: Response's content is not valid HTML:
('Unexpected end tag `li` (Line 347, Column 24)', (347, 24))

======================================================================
FAIL: test_idresolve_is_up (public.tests.IdresolveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/public/tests.py", line 25, in test_idresolve_is_up
    assert doi_lookup(example_doi1) is not None
AssertionError

----------------------------------------------------------------------
Ran 79 tests in 1955.542s

FAILED (failures=2, errors=1)
```

**Comment by bbusenius** [comment]
For the test blowing up on `http://marklogic.lib.uchicago.edu:8011/admin/gimme.xqy?collection=institution%2FUniversity%20of%20Chicago`, I've determined that the `marklogic` IP is locked down to campus or Library IPs. That's why that one is failing.

**Comment by bbusenius** [comment]
I fixed the first test failure, outlined in the initial ticket. Apparently there was some invalid HTML due to a redundant `</li>` close tag in the main navigation. There are still more lib_collections tests failing, however. I'm punting this to @bufordrat since he wanted to look at it when he got back.

**Comment by bufordrat** [comment]
Yeah, the Mark Logic server is locked down to campus.  `idresolve` should be accessible off-campus though; running tests now from on-campus to see what's still broken.

**Comment by bbusenius** [comment]
We'll have to do something with that test then. We definitely need tests to complete successfully off campus, especially if we are to bring Travis CI back. But even if we don't, we'll still want them to pass.

**Comment by bufordrat** [comment]
Yeah, so I guess we need to provide some URL to fall back to in the event that that one fails?  Looks like the Mark Logic URL is coming from the Finding Aids page.

**Comment by bufordrat** [comment]
For `test_collections_digital`, I think maybe the URL is off?  The test says:
```
        request = self.factory.get('/collection/?view=collections&digital=on')
```
But isn't the correct URL this?
```
        request = self.factory.get('/collex/?digital=on&view=collections')
```

**Comment by bbusenius** [comment]
That's what I thought when I first looked at it too. That's what I was talking about above (I may have edited that part out of the ticket after I looked at it closer though) but it turned out not to be a problem. I'm not sure what black magic is causing that, I think perhaps this part in the `urls.py` is causing it to not be a problem: `url(r'^collex/collections/$', RedirectView.as_view(url='/collex/')),`. In any event, that test has always passed before and I don't think that's what's breaking the tests now. Changing it had no effect (I tried that).

**Comment by bufordrat** [comment]
> That's what I thought when I first looked at it too. That's what I was talking about above (I may have edited that part out of the ticket after I looked at it closer though) but it turned out not to be a problem. I'm not sure what black magic is causing that, I think perhaps this part in the `urls.py` is causing it to not be a problem: `url(r'^collex/collections/$', RedirectView.as_view(url='/collex/')),`. In any event, that test has always passed before and I don't think that's what's breaking the tests now. Changing it had no effect (I tried that).

Gotcha.  I see now that that was the one that got thrown by the missing `</li>` tag.

**Comment by bufordrat** [comment]
For `test_all_live_public_pages_for_200_or_redirect_with_anonymous_user`, it looks like the `findingaids` app is querying the Mark Logic server to get the names of all of Special Collections' Finding Aids, so that it can then display them in a table.  Since Mark Logic is blocked from off campus, there's no way to get a 200 status code on the Finding Aids page when running the tests from off campus.  

Could we either:

- set Travis up to ssh to campus to run tests
- open Mark Logic up to the WAN, but lock API calls down with OAuth2 or something

Or something less drastic, perhaps...

**Comment by bufordrat** [comment]
`test_idresolve_is_up` is throwing me, because `idresolve` is accessible to the WAN.  For example, I can `curl` it no problem from my home machine.  

I usually run my Vagrant VM from my on-campus machine, but I will set it up on my home machine to see if this test fails there as well.

**Comment by bbusenius** [comment]
I'm inclined to think that we don't want to require tests to be run on campus. I'm not sure if that's possible with Travis but I wouldn't want to do it even if it was. I'm always running them from my local machine now. I feel like they should work like that. Was the locking down of the Mark Logic server something we did recently or did we not use it on finding aids before? I'm out of the loop on this one but what I can say is that these tests always worked before. I'm assuming something changed

**Comment by bufordrat** [comment]
Good question.  The Mark Logic has been locked down since I started using it, but that was only starting earlier this year.  @johnjung do you happen to know whether restricting the Mark Logic server to on-campus IPs is a recent thing?

**Comment by bbusenius** [comment]
I just looked at the `test_all_live_public_pages_for_200_or_redirect_with_anonymous_user` and the `findingaids/models.py` this morning and can see what's going on. This was likely always a problem:

1. This test has already been written to _not_ run in Travis
2. I was always running these tests from `xibalba` in the past
3. This code is really old

We never noticed this problem because Travis was ignoring it and we didn't happen to be running tests off campus. It's likely that nothing changed. This must have always been a problem.

I think `findingaids/models.py` needs to be cleaned up. 

1. The base url and port number should be coming from one place in the config
2. There should be probably be an abstract getter method that makes the request and this should have a safe fallback for failure that doesn't blow up the page
3. The code needs to be linted

That's the way I think we should approach this.

**Comment by bufordrat** [comment]
Aha!  Thanks; that's quite clarifying.

**Comment by bufordrat** [comment]
Re: (1), I tried refactoring the port number and base URL into `settings/base.py`.  Re-running tests now.  Re: (2), what should happen when the connection to Mark Logic fails to make `test_all_live_public_pages_for_200_or_redirect_with_anonymous_user` happy?  Redirect to `www.lib.uchicago.edu`?

**Comment by bbusenius** [comment]
I was hoping that we could just return some empty xml or do a try catch in the getter method in the `models.py`. That way the page would still display and we wouldn't need to do anything special for the test. In other words, if we abstracted these:

```
            r = urllib.request.urlopen(
                "%s:%i%s" % (
                    MARKLOGIC_BASE,
                    MARKLOGIC_FINDINGAIDS_PORT,
                    route,
                )
            )
```

Into a getter method, we could just handle it once and the pages would still load. Don't take that too literally because I'm not trying to be too prescriptive. There are probably lots of different ways to handle it, just so long as methods like `get_browses` and `get_digitized_content` return something valid and/or don't blow up.

**Comment by bbusenius** [comment]
Because right now, those pages actually blow up. I'm assuming this would also happen if marklogic went down for some reason. It's not something I'm too worried about but it would be nice to handle. In any event, if we do that we won't need to touch the test, I'm hoping

**Comment by bbusenius** [comment]
Edit: I guess you weren't saying to edit the test either. Well either way, whatever makes the most sense but if we do the redirect, that will happen when marklogic isn't available, e.g. on my dev machine. I'm not too worried about it if that's what you want to do but I might prefer seeing the blank page.

**Comment by bufordrat** [comment]
If I have `get_browses` return an empty list and don't change anything else, the page displays "All Finding Aids" followed by nothing at all.  So that fixes the blowing up problem, but perhaps it would be nicer to have it display some sort of "we are having an internal server problem; please contact xyz@uchicago.edu to let us know" error message?  What do you think?

**Comment by bbusenius** [comment]
Yes, something like that would be very nice. That's a very elegant way to do it and much better for the user.

**Comment by bufordrat** [comment]
Ok; I put a draft of these suggested changes up on the branch.  I have a stub in for the error message for now, but once we get the actual error message from David, we can just change those two lines of the template.

**Comment by bbusenius** [comment]
I confirmed with @dbietila that we can use the https://www.lib.uchicago.edu/research/help/ask-librarian/ask-contact/ form for contact.
